name: ci

on:
  push:
    branches: [ master ]
  # the following triggers are for testing purposes only. remove before merge.
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ruby and install deps
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
          bundler: default

      - name: Run lint
        run: bundle exec rubocop

      - name: Build plugin
        run: bundle exec rake build

      - name: Run tests
        run: bundle exec rake test

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: false
          file: docker/Dockerfile
          context: .
